[build-system]
build-backend = "pdm.backend"
requires = [ "pdm-backend" ]

[project]
name = "zeed-pay-viewer"
version = "0.0.0"
description = "python+qt based pay viewer"
license = { file = "LICENSE" }
requires-python = ">=3.12,<3.15"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "jdk4py>=21.0.4.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.2",
    "pyside6-essentials>=6.10.1",
    "pythonqwt>=0.15",
    "selenium>=4.22",
    "tabula-py[jpype]>=2.9.3",
    "zeed-guilib>=0.0.13",
]
[[project.authors]]
name = "ZeeD"
email = "vito.detullio@gmail.com"
[project.gui-scripts]
pay-viewer = "payviewer.mainui:main"
[project.scripts]
pay-settings = "paysettings:main"
[project.urls]
Homepage = "https://github.com/ZeeD/pay-viewer"
Repository = "https://github.com/ZeeD/pay-viewer.git"

[dependency-groups]
dev = [
    "coverage>=7.6.10",
    "mypy>=1.10.1",
    "pandas-stubs>=2.2.2.240603",
    "pyproject-fmt>=2.5.1",
    "pytest>=8.3.2",
    "ruff>=0.5",
]

[tool.pdm]
distribution = true
plugins = [ "pdm-bump" ]
[tool.pdm.build]
excludes = [ "demo", "tests" ]
[tool.pdm.scripts]
_.env = { PYTHONPATH = "src:tests:demo:stubs" }
bump_and_publish = { composite = [
    "pdm bump patch --commit --tag",
    "pdm publish",
    "git push",
    "git push --tags",
] }
lint = { composite = [
    "pyproject-fmt pyproject.toml",
    "ruff format {args:.}",
    "ruff check {args:.}",
    "mypy {args:.}",
], keep_going = true }
pay-settings = "pay-settings"
start = "pay-viewer"
tabula = """
.venv/lib/python3.13/site-packages/jdk4py/java-runtime/bin/java
--add-opens java.base/java.util.zip=ALL-UNNAMED
--add-opens java.desktop/sun.java2d=ALL-UNNAMED
-Dfile.encoding=utf-8
-Xms256M -Xmx1024M
-Dtabula.openBrowser=true
-jar bin/tabula-win-1.2.1/tabula/tabula.jar
"""
test = { composite = [
    "coverage run -m unittest discover --verbose --locals --failfast --catch --start-directory tests {args}",
    "coverage report",
    "coverage erase",
] }

[tool.ruff]
line-length = 80
src = [ "demo", "src", "stubs", "tests" ]
fix = true
[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true
docstring-code-format = true
[tool.ruff.lint]
select = [ "ALL" ]
ignore = [
    "ANN1",
    "COM812",
    "D1",
    "D203",
    "D213",
    "ISC001",
    "PT009",
    "PT027",
    "Q001",
    "Q002",
    "TD002",
    "TD003",
    "CPY001"
]
extend-per-file-ignores."stubs/**/*.pyi" = [
    "FBT001",
    "FBT002",
    "N802",
    "N803",
    "N815",
    "PLR0913",
]
flake8-annotations.allow-star-arg-any = true
flake8-quotes.docstring-quotes = "single"
flake8-quotes.inline-quotes = "single"
flake8-quotes.multiline-quotes = "single"
flake8-type-checking.quote-annotations = true
isort.force-single-line = true

[tool.pyproject-fmt]
column_width = 80
indent = 4
table_format = "long"

[tool.mypy]
mypy_path = [ "src", "tests", "demo", "stubs" ]
strict = true
warn_unused_configs = true
overrides = [
    { module = [ "payviewer.automation" ], disable_error_code = "no-untyped-call" },
]

[tool.coverage.report]
show_missing = true
skip_empty = true
sort = "Cover"
[tool.coverage.run]
branch = true
source = [ "src", "tests" ]
