from pathlib import Path

from openpyxl.worksheet.worksheet import Worksheet

class Workbook:
    def __init__(self, *, write_only: bool) -> None: ...
    def create_sheet(self, title: str | None = None) -> Worksheet: ...
    def save(self, filename: Path) -> None: ...
