class QwtPointArrayData:
    def xData(self) -> list[float]: ...
    def yData(self) -> list[float]: ...

class QwtSeriesStore:
    def data(self) -> QwtPointArrayData | None: ...
    def setData(self, series: QwtPointArrayData | None) -> None: ...
